name: kicad-export

on:
#   push:
#     paths:
#     - '**.sch'
#     - '**.kicad_pcb'
  pull_request:
   paths:
     - '**.sch'
     - '**.kicad_pcb'

#on: push

jobs:
  kicad-export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.0
      name: kiplot-SuperPower-uC
      with:
      # Required - kiplot config file
        config: config.kiplot.yaml
      # optional - prefix to output defined in config
        dir: .generated/SuperPower-uC
      # optional - schematic file
        schema: 'SuperPower-uC/original/SuperPower-uC-KiCad.sch'
      # optional - PCB design file
        board: 'SuperPower-uC/original/SuperPower-uC-KiCad.kicad_pcb'
    - uses: nerdyscout/kicad-exports@v2.0
      name: kiplot-SuperPower-RPi
      with:
      # Required - kiplot config file
        config: config.kiplot.yaml
      # optional - prefix to output defined in config
        dir: .generated/SuperPower-RPi
      # optional - schematic file
        schema: 'SuperPower-RPi/SuperPower-RPi-KiCAD/SuperPower-RPi-KiCAD.sch'
      # optional - PCB design file
        board: 'SuperPower-RPi/SuperPower-RPi-KiCAD/SuperPower-RPi-KiCAD.kicad_pcb'
#    - name: upload results
#      uses: actions/upload-artifact@v2
#      with:
#        name: build
#        path: build
    - name: git commit && git push 
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update autogenerated files'
        push-branch: ${{ steps.branch.outputs.current }}
        name: kicad-exports
        rebase: 'true'
        files: .generated/SuperPower-uC* .generated/SuperPower-RPi*

